name: On Push Workflow

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.19.4"
      - name: Build
        run: go build
      - name: Get current date
        id: get-current-date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ steps.get-current-date.outputs.date }}"
          files: ./gorrola

permissions:
  contents: write
